# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - deploy-to-kube.sh
    - .gitignore
    - LICENSE
    - README.md
    

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'dsalamanca.azurecr.io/python-sql:$(build.buildId)'

steps:
- task: CmdLine@2
  inputs: tar cvzf estustar_ci.tgz static/ templates/ application.py requirements.txt

- task: Docker@1
  displayName: 'Build an image'
  inputs:
    imageName: '$(imageName)'

- task: Docker@1
  displayName: Login
  inputs:
    azureSubscriptionEndpoint: 'Inside Sales Sub (851e14db-af76-4238-93b5-368169c46a6e)'
    azureContainerRegistry: dsalamanca.azurecr.io
    command: login

- task: Docker@1
  displayName: 'Push an image'
  inputs:
    command: 'push'
    imageName: '$(imageName)'

- task: HelmDeploy@0
  displayName: 'helm init'
  inputs:
    command: init
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Inside Sales Sub (851e14db-af76-4238-93b5-368169c46a6e)'
    azureResourceGroup: 'K8sAzureCNI'
    KubernetesCluster: 'K8sAzureCNI'
    arguments: '--client-only'

- task: HelmDeploy@0
  displayName: 'helm package'
  inputs:
    command: package
    chartPath: './EstusFlask'
    save: false


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts: drop'
