# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'dsalamanca.azurecr.io/python-sql:$(build.buildId)'

steps:
- task: Docker@1
  displayName: 'Build an image'
  inputs:
    imageName: '$(imageName)'
- task: Docker@1
  displayName: Login
  inputs:
    azureSubscriptionEndpoint: 'Inside Sales Sub'
    azureContainerRegistry: dsalamanca.azurecr.io
    command: login
- task: Docker@1
  displayName: 'Push an image'
  inputs:
    command: 'push'
    imageName: '$(imageName)'