apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: python-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pysql-deploy
  minReplicas: 3
  maxReplicas: 15
  metrics:
  - resource:
        name: memory
        targetAverageUtilization: 50
    type: Resource

