apiVersion: apps/v1
kind: Deployment
metadata:
  name: pysql-deploy
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: pysql
        image: dsalamanca.azurecr.io/python-sql:v1
        ports:
        - containerPort: 8080
        env:
          - name: DB_SERVER
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: dbserver
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: dbname
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: dbuser
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: dbpass
      imagePullSecrets:
      - name: regcred
      restartPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    app: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
