apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: {{ .Values.minreplica }}
  maxReplicas: {{ .Values.maxreplica }}
  metrics:
  - resource:
        name: memory
        targetAverageUtilization: 50
    type: Resource

