apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "estusflask.labels" . | indent 4 }}
spec:
  type: LoadBalancer
  selector:
    {{- include "estusflask.labels" . | indent 4 }}
  ports:
  - port: {{ .Values.serviceport }}
    targetPort: 8080
    protocol: TCP